### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by 72636c** [seek-oss/eslint-config-seek#62]
https://eslint.org/blog/2021/10/eslint-v8.0.0-released

- [ ] `@typescript-eslint/eslint-plugin`: Upgrade to https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0
- [ ] `@typescript-eslint/parser`: Upgrade to https://github.com/typescript-eslint/typescript-eslint/releases/tag/v5.0.0
- [ ] `babel-eslint`: Migrate to https://www.npmjs.com/package/@babel/eslint-parser
- [ ] `babel-eslint`: Upgrade to https://github.com/babel/babel/releases/tag/v7.16.0
- [ ] `eslint-config-prettier`: Upgrade to https://github.com/prettier/eslint-config-prettier/blob/HEAD/CHANGELOG.md#version-800-2021-02-21?
- [ ] `eslint-import-resolver-node`: Validate that this works with latest `eslint-plugin-import`
- [x] `eslint-plugin-css-modules`: #64
- [ ] ⛔ `eslint-plugin-cypress`: https://github.com/cypress-io/eslint-plugin-cypress/issues/89
- [x] `eslint-plugin-flowtype`: #64
- [ ] `eslint-plugin-import`: Upgrade to https://github.com/import-js/eslint-plugin-import/releases/tag/v2.25.0
- [x] `eslint-plugin-jest`: #60 https://github.com/seek-oss/eslint-config-seek/releases/tag/v7.0.9
- [ ] `eslint-plugin-react`: Upgrade to https://github.com/yannickcr/eslint-plugin-react/releases/tag/v7.27.0
- [ ] `eslint-plugin-react-hooks`: Upgrade to https://github.com/facebook/react/pull/22248#issuecomment-964176674
